parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\AiDescriptionService:
        arguments:
            $openAiApiKey: '%env(default::string:OPENAI_API_KEY)%'
            $huggingFaceApiKey: '%env(default::string:HUGGINGFACE_API_KEY)%'
            $aiProvider: '%env(default::string:AI_PROVIDER)%'

    App\Service\MediaTranscodingService:
        arguments:
            $cloudinaryCloudName: '%env(default::string:CLOUDINARY_CLOUD_NAME)%'
            $cloudinaryApiKey: '%env(default::string:CLOUDINARY_API_KEY)%'
            $cloudinaryApiSecret: '%env(default::string:CLOUDINARY_API_SECRET)%'
            $useCloudinary: '%env(bool:USE_CLOUDINARY)%'

